AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for an EC2 instance with Security Group and existing IAM Instance Profile.

Resources:
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0e309a5f3a6dd97ea
      InstanceType: t2.micro
      KeyName: AWS-W2K16
      SecurityGroups:
        - !Ref MySecurityGroup
      IamInstanceProfile: AmazonSSM-EC2-Profile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Hello World from $(hostname -f)" > /var/www/html/index.html
